name: GitHub secrets

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  secrets-in-github:
    runs-on: windows-latest
    steps:
      - name: step 1 echo
        run: |
          echo "mask"
          echo ${{ secrets.MY_SECRET }} | base64
