name: GitHub secrets

on:
  push: 
    branch: [ main ]
jobs:
  secrets-in-github:
    runs-on: windows-latest
    steps:
        - name: step 1 echo
          run: |
            echo "mask"
            echo ${{secrets.my_secrets}}
